/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-14 09:40:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/views/HeaderFooter/header.jsp", Long.valueOf(1681463558091L));
    _jspx_dependants.put("/views/HeaderFooter/footer.jsp", Long.valueOf(1681463021867L));
    _jspx_dependants.put("/WEB-INF/tagLib.jsp", Long.valueOf(1681462244345L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1681386918978L));
    _jspx_dependants.put("jar:file:/C:/Users/aly_d/Desktop/LiveProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/NationOfBaka/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("     <!-- Css Styles -->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/plyr.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./assets/css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     \r\n");
      out.write("        <!-- Header Section Begin -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-2\">\r\n");
      out.write("                    <div class=\"header__logo\">\r\n");
      out.write("                        <a href=\"./index.html\">\r\n");
      out.write("                            <img src=\"img/logo.png\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"header__nav\">\r\n");
      out.write("                        <nav class=\"header__menu mobile-menu\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li class=\"active\"><a href=\"./index.html\">Homepage</a></li>\r\n");
      out.write("                                <li><a href=\"./categories.html\">Categories <span class=\"arrow_carrot-down\"></span></a>\r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                        <li><a href=\"./categories.html\">Categories</a></li>\r\n");
      out.write("                                        <li><a href=\"./anime-details.html\">Anime Details</a></li>\r\n");
      out.write("                                        <li><a href=\"./anime-watching.html\">Anime Watching</a></li>\r\n");
      out.write("                                        <li><a href=\"./blog-details.html\">Blog Details</a></li>\r\n");
      out.write("                                        <li><a href=\"./signup.html\">Sign Up</a></li>\r\n");
      out.write("                                        <li><a href=\"./login.html\">Login</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"./blog.html\">Our Blog</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Contacts</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-2\">\r\n");
      out.write("                    <div class=\"header__right\">\r\n");
      out.write("                        <a href=\"#\" class=\"search-switch\"><span class=\"icon_search\"></span></a>\r\n");
      out.write("                        <a href=\"./login.html\"><span class=\"icon_profile\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- Hero Section Begin -->\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"hero__slider owl-carousel\">\r\n");
      out.write("                <div class=\"hero__items set-bg\" data-setbg=\"assets/img/hero/hero-1.jpg\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <div class=\"label\">Adventure</div>\r\n");
      out.write("                                <h2>Fate / Stay Night: Unlimited Blade Works</h2>\r\n");
      out.write("                                <p>After 30 days of travel across the world...</p>\r\n");
      out.write("                                <a href=\"#\"><span>Watch Now</span> <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"hero__items set-bg\" data-setbg=\"img/hero/hero-1.jpg\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <div class=\"label\">Adventure</div>\r\n");
      out.write("                                <h2>Fate / Stay Night: Unlimited Blade Works</h2>\r\n");
      out.write("                                <p>After 30 days of travel across the world...</p>\r\n");
      out.write("                                <a href=\"#\"><span>Watch Now</span> <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"hero__items set-bg\" data-setbg=\"img/hero/hero-1.jpg\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <div class=\"label\">Adventure</div>\r\n");
      out.write("                                <h2>Fate / Stay Night: Unlimited Blade Works</h2>\r\n");
      out.write("                                <p>After 30 days of travel across the world...</p>\r\n");
      out.write("                                <a href=\"#\"><span>Watch Now</span> <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("      <!-- Hero Section End -->");
      out.write("    <section>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h1>Bienvenue sur notre site Manga et Anime !</h1>\r\n");
      out.write("    \r\n");
      out.write("            <p>Vous trouverez ici une large sélection de mangas, y compris des\r\n");
      out.write("                titres populaires tels que Naruto, One Piece, Bleach, Dragon Ball, et\r\n");
      out.write("                bien d'autres encore. Parcourez notre catalogue pour découvrir de\r\n");
      out.write("                nouveaux titres ou utilisez notre barre de recherche pour trouver des\r\n");
      out.write("                titres spécifiques.</p>\r\n");
      out.write("    \r\n");
      out.write("            <p>Pour accéder à notre catalogue complet, vous devez vous\r\n");
      out.write("                connecter à votre compte ou créer un compte gratuitement si vous n'en\r\n");
      out.write("                avez pas encore. Une fois connecté, vous pouvez ajouter des mangas à\r\n");
      out.write("                votre panier et passer une commande en toute sécurité.</p>\r\n");
      out.write("    \r\n");
      out.write("            <!-- <a href=\"connexion.html\">Se connecter</a> | <a href=\"inscription.html\">S'inscrire</a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"banner\">\r\n");
      out.write("                <img\r\n");
      out.write("                    src=\"https://th.bing.com/th/id/R.11e50ed255f216a0101c68789b927e72?rik=krpErk%2f1qlFGhQ&riu=http%3a%2f%2fblogcenterblog46.b.l.pic.centerblog.net%2f35d75835.jpg&ehk=93amU%2fQit8rEsSH8wmSNsHa8Wp5dBv2BMgXfwIJf8WE%3d&risl=&pid=ImgRaw&r=0\"\r\n");
      out.write("                    alt=\"Manga and Anime\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>\r\n");
      out.write("                Retrouvez ici les derniers chapitres de vos mangas préférés\r\n");
      out.write("                ainsi que les épisodes des derniers anime à la mode.\r\n");
      out.write("            </p>\r\n");
      out.write("            <h2>Nouveautés</h2>\r\n");
      out.write("            <div class=\"new-releases\">\r\n");
      out.write("                <div class=\"new-release\">\r\n");
      out.write("                    <a href=\"https://sekai.one/\"> <img\r\n");
      out.write("                        src=\"https://wallpapercave.com/dwp1x/wp9995088.jpg\" alt=\"One Piece\">\r\n");
      out.write("                        <h3>One Piece</h3>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"new-release\">\r\n");
      out.write("                    <a href=\"https://sekai.one/\"> <img\r\n");
      out.write("                        src=\"https://wallpapercave.com/dwp1x/wp4445437.jpg\"\r\n");
      out.write("                        alt=\"Demon Slayer\">\r\n");
      out.write("                        <h3>Demon Slayer</h3>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"new-release\">\r\n");
      out.write("                    <a href=\"https://sekai.one/\"> <img\r\n");
      out.write("                        src=\"https://wallpapercave.com/dwp1x/wp10948343.jpg\"\r\n");
      out.write("                        alt=\"My Hero Academia\">\r\n");
      out.write("                        <h3>My Hero Academia</h3>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("     \r\n");
      out.write("    <!-- Footer Section Begin -->\r\n");
      out.write("    <footer class=\"footer text-light pt-4 pb-4\">\r\n");
      out.write("        <div class=\"page-up\">\r\n");
      out.write("            <a href=\"#\" id=\"scrollToTopButton\"><span class=\"arrow_carrot-up\"></span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"footer__logo\">\r\n");
      out.write("                        <a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"footer__nav\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"active\"><a href=\"./index.html\">Homepage</a></li>\r\n");
      out.write("                            <li><a href=\"./categories.html\">Categories</a></li>\r\n");
      out.write("                            <li><a href=\"./blog.html\">Our Blog</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Contacts</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container text-white-50\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"single-footer f-contact\">\r\n");
      out.write("                        <h3>Contactez nous !</h3>\r\n");
      out.write("                        <p class=\"phone\">TÃ©lÃ©phone : <a href=\"tel:0123456789\"\r\n");
      out.write("                                class=\"link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">01\r\n");
      out.write("                                23 45 67 89</a></p>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><span>Lundi-Vendredi : </span> 09:00 - 20:00</li>\r\n");
      out.write("                            <li><span>Samedi : </span> 10:00 - 18:00</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p class=\"mail\">\r\n");
      out.write("                            <a href=\"mailto:contact@afpazon.fr\"\r\n");
      out.write("                                class=\"link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">contact@afpazon.fr</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-12 text-center\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h3>Tout d'abord nous allons voir quel est la signification <em class=\"fs-6\"> du mot MANGA\r\n");
      out.write("                                ?</em></h3>\r\n");
      out.write("                        <p>Le mot Â«mangaÂ» æ¼«ç» ou ã¾ãã est constituÃ© de 2 kanji ou chacun a un sens particulier :\r\n");
      out.write("                            Le premier kanji Â«manÂ» æ¼« signifie distraction, lÃ©gÃ¨retÃ©, puretÃ©...\r\n");
      out.write("                            Le second, Â«gaÂ» ç» ou ã en hiragana, dÃ©signe la peinture, lâillustration, le dessin..\r\n");
      out.write("\r\n");
      out.write("                            La combinaison de ces 2 kanjis pourraient se traduire par Â«dessins au trait nerveuxÂ» /\r\n");
      out.write("                            Â«esquisses fantaisisteÂ» ou bien par exemple \"illustration distractive\". Le peintre Hokusai\r\n");
      out.write("                            (rÃ©alisateur maÃ®tre dans l'art des estampes), a crÃ©e cet appellation en unissant ces 2\r\n");
      out.write("                            kanjis, il a inventer cela pour dÃ©signer les recueils de caricatures et de croquis quâil\r\n");
      out.write("                            avait rÃ©alisÃ© au dÃ©but du XXÃ¨me siÃ¨cle.\r\n");
      out.write("                            De nos jours, le mot manga dÃ©signe la BD (bande dessinÃ©e).</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"d-flex flex-column\">\r\n");
      out.write("                        <h3>Information</h3>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                            <li><a href=\"\"\r\n");
      out.write("                                    class=\"link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">A\r\n");
      out.write("                                    propos</a></li>\r\n");
      out.write("                            <li><a href=\"cgv\"\r\n");
      out.write("                                    class=\"link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover\">Conditions\r\n");
      out.write("                                    GÃ©nÃ©rales de Vente</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"payment-gateway\">\r\n");
      out.write("                    <span>Partenaire de paiement </span> <img src=\"./assets/images/credit-cards-footer.png\" alt=\"#\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-content\">\r\n");
      out.write("                    <div class=\"row align-middle\">\r\n");
      out.write("                        <div class=\"col-lg-4 col-12\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-4 col-12 text-center\">\r\n");
      out.write("                            <div class=\"copyright\">\r\n");
      out.write("                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                                    Copyright &copy;\r\n");
      out.write("                                    <script>document.write(new Date().getFullYear());</script> All rights reserved |\r\n");
      out.write("                                    This template\r\n");
      out.write("                                    is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("                                        href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Section End -->\r\n");
      out.write("    \r\n");
      out.write(" <!-- Page Preloder -->\r\n");
      out.write(" <div id=\"preloder\">\r\n");
      out.write("    <div class=\"loader\">\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- Js Plugins -->\r\n");
      out.write("<script src=\"./assets/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/player.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/mixitup.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/jquery.slicknav.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
